version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile.dev
    environment:
      APP_GRPC_PORT: 5000
      APP_ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5000:5000
    volumes:
      - ./cmd:/app/cmd
      - ./pkg:/app/pkg
      - ./main.go:/app/main.go

  elasticsearch:
    image: elasticsearch:7.17.3
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    restart: always
    ports:
      - 9200:9200
